version: "3.7"
services:
  evaluation_bridge:
    build:
      context: .
    init: true
    container_name: evaluation_bridge
    volumes:
      - "/var/run/docker:/var/run/docker"
      - "/var/run/docker.pid:/var/run/docker.pid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./hidden_service:/var/lib/tor/hidden_service"
