version: "3.7"
services:
  moduleleve:
    build:
      context: .
    init: true
    network_mode: host
    volumes:
      - "/var/run/docker:/var/run/docker"
      - "/var/run/docker.pid:/var/run/docker.pid"
      - "/var/run/docker.sock:/var/run/docker.sock"